"""Mirror of pi coding-agent src/core/extensions/index.ts."""

from .loader import (
    ExtensionAPI,
    clear_extension_cache,
    create_extension_runtime,
    discover_and_load_extensions,
    discover_extensions_in_dir_blocking,
    load_extension_from_factory,
    load_extensions,
    load_extensions_cached,
    resolve_extension_entries_blocking,
)
from .runner import (
    BoundaryDispatchResult,
    ExtensionRunner,
    InputEventResult,
    ResourcesDiscoverPaths,
    emit_project_trust_event,
    emit_session_shutdown_event,
)
from .types import (
    AgentActivityOutcome,
    BoundaryContextPreview,
    Extension,
    ExtensionContext,
    ExtensionError,
    ExtensionFlag,
    ExtensionLoadError,
    ExtensionLoadWarning,
    ExtensionRuntime,
    ExtensionShortcut,
    ExtensionVirtualModel,
    LoadExtensionsResult,
    RegisteredCommand,
    RegisteredTool,
    ResolvedCommand,
    ToolDefinition,
    ToolRendererResolver,
    ToolRenderers,
)
from .wrapper import wrap_registered_tool, wrap_registered_tools


__all__ = [
    "AgentActivityOutcome",
    "BoundaryContextPreview",
    "BoundaryDispatchResult",
    "Extension",
    "ExtensionAPI",
    "ExtensionContext",
    "ExtensionError",
    "ExtensionFlag",
    "ExtensionLoadError",
    "ExtensionLoadWarning",
    "ExtensionRunner",
    "ExtensionRuntime",
    "ExtensionShortcut",
    "ExtensionVirtualModel",
    "InputEventResult",
    "LoadExtensionsResult",
    "RegisteredCommand",
    "RegisteredTool",
    "ResolvedCommand",
    "ResourcesDiscoverPaths",
    "ToolDefinition",
    "ToolRendererResolver",
    "ToolRenderers",
    "clear_extension_cache",
    "create_extension_runtime",
    "discover_and_load_extensions",
    "discover_extensions_in_dir_blocking",
    "emit_project_trust_event",
    "emit_session_shutdown_event",
    "load_extension_from_factory",
    "load_extensions",
    "load_extensions_cached",
    "resolve_extension_entries_blocking",
    "wrap_registered_tool",
    "wrap_registered_tools",
]
