"""Mirror of pi mcp src/oauth/index.ts: the MCP OAuth client subset."""

from .callback import OAuthCallback, OAuthCallbackPage, OAuthCallbackServer
from .discovery import (
    build_authorization_server_discovery_urls,
    discover_authorization_server_metadata,
    discover_oauth_server_info,
    discover_protected_resource_metadata,
    parse_www_authenticate,
    resource_url_from_server_url,
    select_resource,
)
from .errors import (
    McpOAuthAuthorizationRequiredError,
    OAuthError,
    OAuthInsecureEndpointError,
    OAuthIssuerMismatchError,
    OAuthRegistrationError,
)
from .flow import (
    AddClientAuthentication,
    AuthorizationStart,
    CredentialsKind,
    OAuthClientMetadataDocument,
    OAuthClientProvider,
    OAuthFlowOptions,
    OAuthFlowResult,
    TokenRequestOptions,
    adapt_oauth_provider,
    authorize_mcp,
    exchange_authorization_code,
    refresh_authorization,
    register_client,
    start_authorization,
    step_up_scope,
)
from .provider import McpOAuthProvider, McpOAuthState, McpOAuthStateStore, MemoryOAuthStateStore
from .types import (
    AuthorizationServerMetadata,
    OAuthChallenge,
    OAuthClientInformation,
    OAuthClientInformationFull,
    OAuthClientInformationMixed,
    OAuthClientMetadata,
    OAuthDiscoveryState,
    OAuthProtectedResourceMetadata,
    OAuthServerInfo,
    OAuthTokens,
)


__all__ = [
    "AddClientAuthentication",
    "AuthorizationServerMetadata",
    "AuthorizationStart",
    "CredentialsKind",
    "McpOAuthAuthorizationRequiredError",
    "McpOAuthProvider",
    "McpOAuthState",
    "McpOAuthStateStore",
    "MemoryOAuthStateStore",
    "OAuthCallback",
    "OAuthCallbackPage",
    "OAuthCallbackServer",
    "OAuthChallenge",
    "OAuthClientInformation",
    "OAuthClientInformationFull",
    "OAuthClientInformationMixed",
    "OAuthClientMetadata",
    "OAuthClientMetadataDocument",
    "OAuthClientProvider",
    "OAuthDiscoveryState",
    "OAuthError",
    "OAuthFlowOptions",
    "OAuthFlowResult",
    "OAuthInsecureEndpointError",
    "OAuthIssuerMismatchError",
    "OAuthProtectedResourceMetadata",
    "OAuthRegistrationError",
    "OAuthServerInfo",
    "OAuthTokens",
    "TokenRequestOptions",
    "adapt_oauth_provider",
    "authorize_mcp",
    "build_authorization_server_discovery_urls",
    "discover_authorization_server_metadata",
    "discover_oauth_server_info",
    "discover_protected_resource_metadata",
    "exchange_authorization_code",
    "parse_www_authenticate",
    "refresh_authorization",
    "register_client",
    "resource_url_from_server_url",
    "select_resource",
    "start_authorization",
    "step_up_scope",
]
