"""Mirror of pi tui src/index.ts (re-exports grow as modules are ported)."""

from .keybindings import (
    TUI_KEYBINDINGS,
    KeybindingsManager,
    get_keybindings,
    set_keybindings,
)
from .keys import (
    Key,
    decode_kitty_printable,
    is_key_release,
    is_key_repeat,
    is_kitty_protocol_active,
    matches_key,
    parse_key,
    set_kitty_protocol_active,
)
from .stdin_buffer import StdinBuffer
from .terminal import (
    ProcessTerminal,
    Terminal,
    is_apple_terminal_session,
    normalize_apple_terminal_input,
    parse_keyboard_protocol_negotiation_sequence,
)
from .terminal_colors import (
    parse_osc11_background_color,
    parse_terminal_color_scheme_report,
)
from .terminal_image import (
    allocate_image_id,
    calculate_image_rows,
    delete_all_kitty_images,
    delete_kitty_image,
    detect_capabilities,
    encode_iterm2,
    encode_kitty,
    get_capabilities,
    get_cell_dimensions,
    get_gif_dimensions,
    get_image_dimensions,
    get_jpeg_dimensions,
    get_png_dimensions,
    get_webp_dimensions,
    hyperlink,
    image_fallback,
    render_image,
    reset_capabilities_cache,
    set_capabilities,
    set_cell_dimensions,
)
from .tui import (
    CURSOR_MARKER,
    TUI,
    Component,
    Container,
    Focusable,
    OverlayHandle,
    is_focusable,
)
from .utils import slice_by_column, truncate_to_width, visible_width, wrap_text_with_ansi


__all__ = [
    "CURSOR_MARKER",
    "TUI",
    "TUI_KEYBINDINGS",
    "Component",
    "Container",
    "Focusable",
    "Key",
    "KeybindingsManager",
    "OverlayHandle",
    "ProcessTerminal",
    "StdinBuffer",
    "Terminal",
    "allocate_image_id",
    "calculate_image_rows",
    "decode_kitty_printable",
    "delete_all_kitty_images",
    "delete_kitty_image",
    "detect_capabilities",
    "encode_iterm2",
    "encode_kitty",
    "get_capabilities",
    "get_cell_dimensions",
    "get_gif_dimensions",
    "get_image_dimensions",
    "get_jpeg_dimensions",
    "get_keybindings",
    "get_png_dimensions",
    "get_webp_dimensions",
    "hyperlink",
    "image_fallback",
    "is_apple_terminal_session",
    "is_focusable",
    "is_key_release",
    "is_key_repeat",
    "is_kitty_protocol_active",
    "matches_key",
    "normalize_apple_terminal_input",
    "parse_key",
    "parse_keyboard_protocol_negotiation_sequence",
    "parse_osc11_background_color",
    "parse_terminal_color_scheme_report",
    "render_image",
    "reset_capabilities_cache",
    "set_capabilities",
    "set_cell_dimensions",
    "set_keybindings",
    "set_kitty_protocol_active",
    "slice_by_column",
    "truncate_to_width",
    "visible_width",
    "wrap_text_with_ansi",
]
