"""Emit the complete Homebrew formula for a built release.

    uv run python scripts/brew_formula.py <version> [dist-dir] > pidrei.rb

The four pidrei distributions exist on no index, so the formula carries each as
a `resource` pointing at the GitHub release asset, with the sha256 taken from
the file that was actually built.

**Third-party resources come from `uv.lock`**, not from
`brew update-python-resources`: the lock already records the exact version,
sdist URL and sha256 of every transitive dependency — the same set the test
suite ran against — while brew's resolver would fetch the *latest* PyPI
releases (it cannot see pidrei's own pins, since pidrei is resolvable from no
index) and rewrite the GitHub-asset resources it does not understand. The
emitted formula is final: copy it into the tap and commit.
"""

import hashlib
import os
import sys
import tomllib


REPO = "gi0baro/pidrei"
# The published distributions; protocol/client/server are workspace-only
# transport remnants (UPSTREAM_EXPERIMENTAL_RULING.md) and are not built.
PACKAGES = ("pidrei", "pidrei_ai", "pidrei_agent", "pidrei_tui")
WORKSPACE_MEMBERS = frozenset(name.replace("_", "-") for name in PACKAGES)

TEMPLATE = """# Generated by scripts/brew_formula.py — do not hand-edit.
# All resources are pinned: pidrei's own from the release assets, third-party
# from uv.lock (the exact set the release's test suite ran against).
class Pidrei < Formula
  include Language::Python::Virtualenv

  desc "Terminal coding agent — a Python port of the pi coding agent"
  homepage "https://github.com/{repo}"
  url "{root_url}"
  sha256 "{root_sha}"
  license "MIT"

  # Free-threaded CPython is mandatory, not a preference.
  depends_on "python-freethreading"
  # The find and grep tools shell out to these; pidrei never downloads binaries.
  depends_on "fd"
  depends_on "ripgrep"
  # Resources build from sdists: tonio and cryptography are Rust extensions,
  # and cryptography links OpenSSL.
  depends_on "rust" => :build
  depends_on "openssl@3"
  # pillow compiles codecs against whatever its setup *detects*, and detection
  # reads the host's pkg-config while the sandboxed compile cannot see host
  # headers — a feature found-but-unreachable fails the whole build (seen with
  # the host's freetype/openjpeg on Linux). Declaring the full codec set makes
  # detection deterministic; jpeg/webp are also load-bearing for image paste.
  depends_on "freetype"
  depends_on "jpeg-turbo"
  depends_on "libtiff"
  depends_on "little-cms2"
  depends_on "openjpeg"
  depends_on "webp"
  uses_from_macos "zlib"

  on_linux do
    depends_on "libxcb"
  end

{pidrei_resources}{third_party_resources}  def install
    virtualenv_install_with_resources(using: "python3.14t")
  end

  test do
    assert_equal "{version}", shell_output("#{{bin}}/pidrei --version").strip
    # `--version` prints the bare version, no program name — on both binaries.
    assert_equal "{version}", shell_output("#{{bin}}/pi3 --version").strip
  end
end
"""

RESOURCE = """  resource "{name}" do
    url "{url}"
    sha256 "{sha}"
  end

"""


def sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def third_party_resources(lock_path: str) -> str:
    """Resource blocks for the runtime dependency closure, from `uv.lock`.

    Walks `dependencies` (never dev groups) from the published workspace members.
    Dependency markers are ignored deliberately: the only conditional edges in
    the tree are PyPy exclusions, and brew installs CPython. A package without
    an sdist in the lock is an error — brew builds resources from source.
    """
    with open(lock_path, "rb") as handle:
        lock = tomllib.load(handle)
    packages = {package["name"]: package for package in lock["package"]}

    closure: set[str] = set()
    stack = list(WORKSPACE_MEMBERS)
    while stack:
        for dependency in packages[stack.pop()].get("dependencies", []):
            if dependency["name"] not in closure:
                closure.add(dependency["name"])
                stack.append(dependency["name"])

    blocks = []
    for name in sorted(closure - WORKSPACE_MEMBERS):
        sdist = packages[name].get("sdist")
        if sdist is None:
            raise SystemExit(f"uv.lock has no sdist for {name!r}; brew resources build from source")
        digest = sdist["hash"].removeprefix("sha256:")
        blocks.append(RESOURCE.format(name=name, url=sdist["url"], sha=digest))
    return "".join(blocks)


def asset_url(version: str, filename: str) -> str:
    return f"https://github.com/{REPO}/releases/download/v{version}/{filename}"


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    version = sys.argv[1].removeprefix("v")
    dist = sys.argv[2] if len(sys.argv) > 2 else "dist"

    missing = []
    paths = {}
    for name in PACKAGES:
        filename = f"{name}-{version}.tar.gz"
        path = os.path.join(dist, filename)
        if not os.path.exists(path):
            missing.append(filename)
        paths[name] = (filename, path)
    if missing:
        print(f"missing sdists in {dist}/: {', '.join(missing)}", file=sys.stderr)
        return 1

    root_filename, root_path = paths["pidrei"]
    resources = "".join(
        RESOURCE.format(
            name=name.replace("_", "-"),
            url=asset_url(version, paths[name][0]),
            sha=sha256(paths[name][1]),
        )
        for name in PACKAGES
        if name != "pidrei"
    )

    print(
        TEMPLATE.format(
            repo=REPO,
            root_url=asset_url(version, root_filename),
            root_sha=sha256(root_path),
            pidrei_resources=resources,
            third_party_resources=third_party_resources(
                os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "uv.lock")
            ),
            version=version,
        ),
        end="",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
