"""Emit the Homebrew formula for a built release.

    uv run python scripts/brew_formula.py <version> [dist-dir] > pidrei.rb

The five pidrei distributions exist on no index, so the formula carries each as
a `resource` pointing at the GitHub release asset, with the sha256 taken from
the file that was actually built. That is the part a human should never compute
by hand, and the reason this script exists.

**Third-party resources are not generated here.** `brew update-python-resources
pidrei.rb` fills those in from PyPI, and it is the only sane way to keep ~15
transitive pins current. Run it in the tap after dropping this file in; the
placeholder block below is where it writes.
"""

import hashlib
import os
import sys


REPO = "gi0baro/pidrei"
PACKAGES = ("pidrei", "pidrei_ai", "pidrei_agent", "pidrei_tui", "pidrei_server")

TEMPLATE = """# Generated by scripts/brew_formula.py — do not hand-edit the pidrei resources.
# After copying into the tap, run:  brew update-python-resources pidrei.rb
class Pidrei < Formula
  include Language::Python::Virtualenv

  desc "Terminal coding agent — a Python port of the pi coding agent"
  homepage "https://github.com/{repo}"
  url "{root_url}"
  sha256 "{root_sha}"
  license "MIT"

  # Free-threaded CPython is mandatory, not a preference.
  depends_on "python-freethreading"
  # The find and grep tools shell out to these; pidrei never downloads binaries.
  depends_on "fd"
  depends_on "ripgrep"

{pidrei_resources}
  # <<< brew update-python-resources writes the third-party resources here >>>

  def install
    virtualenv_install_with_resources(using: "python3.14t")
  end

  test do
    assert_equal "{version}", shell_output("#{{bin}}/pidrei --version").strip
    assert_match "pidrei", shell_output("#{{bin}}/pi3 --version")
  end
end
"""

RESOURCE = """  resource "{name}" do
    url "{url}"
    sha256 "{sha}"
  end

"""


def sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def asset_url(version: str, filename: str) -> str:
    return f"https://github.com/{REPO}/releases/download/v{version}/{filename}"


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    version = sys.argv[1].removeprefix("v")
    dist = sys.argv[2] if len(sys.argv) > 2 else "dist"

    missing = []
    paths = {}
    for name in PACKAGES:
        filename = f"{name}-{version}.tar.gz"
        path = os.path.join(dist, filename)
        if not os.path.exists(path):
            missing.append(filename)
        paths[name] = (filename, path)
    if missing:
        print(f"missing sdists in {dist}/: {', '.join(missing)}", file=sys.stderr)
        return 1

    root_filename, root_path = paths["pidrei"]
    resources = "".join(
        RESOURCE.format(
            name=name.replace("_", "-"),
            url=asset_url(version, paths[name][0]),
            sha=sha256(paths[name][1]),
        )
        for name in PACKAGES
        if name != "pidrei"
    )

    print(
        TEMPLATE.format(
            repo=REPO,
            root_url=asset_url(version, root_filename),
            root_sha=sha256(root_path),
            pidrei_resources=resources,
            version=version,
        ),
        end="",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
