"""Mirror of pi mcp src/index.ts: a standalone Model Context Protocol client.

A transport-neutral client core, stdio and Streamable HTTP transports, and an
in-memory transport for tests (`pidrei_mcp.testing`); the OAuth client
subset is `pidrei_mcp.oauth`. Depends on no pidrei package but pidrei-utils
and pidrei-http.
"""

from .auth_provider import AuthProvider, UnauthorizedContext
from .client import McpClient, McpClientOptions, RequestContext, RequestHandler
from .fetch import McpFetch, McpResponse, McpResponseHeaders, default_fetch
from .protocol.content import (
    AudioContent,
    BlobResourceContents,
    CallToolResult,
    ContentAnnotations,
    ContentBlock,
    EmbeddedResourceContent,
    ImageContent,
    LlmContent,
    ResourceLinkContent,
    TextContent,
    TextResourceContents,
    to_llm_content,
)
from .protocol.jsonrpc import (
    JSON_RPC_ERROR_CODES,
    JsonRpcErrorObject,
    JsonRpcErrorResponse,
    JsonRpcId,
    JsonRpcMessage,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    JsonRpcSuccessResponse,
    McpAbortError,
    McpConnectionClosedError,
    McpError,
    McpTimeoutError,
    is_json_rpc_notification,
    is_json_rpc_request,
    is_json_rpc_response,
    parse_json_rpc_message,
)
from .protocol.types import (
    LATEST_PROTOCOL_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
    CancelledNotification,
    ClientCapabilities,
    Implementation,
    InitializeParams,
    InitializeResult,
    ListResourcesResult,
    ListResourceTemplatesResult,
    ListToolsResult,
    ProgressNotification,
    ReadResourceResult,
    Resource,
    ResourceTemplate,
    Root,
    ServerCapabilities,
    SupportedProtocolVersion,
    Tool,
    ToolAnnotations,
    ToolExecution,
)
from .transports.stdio import StdioTransport, StdioTransportOptions
from .transports.streamable_http import (
    McpAuthRequiredError,
    McpHttpError,
    McpSessionExpiredError,
    StreamableHttpReconnectOptions,
    StreamableHttpTransport,
    StreamableHttpTransportOptions,
)
from .transports.transport import (
    McpTransport,
    McpTransportCloseListener,
    McpTransportErrorListener,
    McpTransportMessageListener,
    SendResult,
)


__all__ = [
    "JSON_RPC_ERROR_CODES",
    "LATEST_PROTOCOL_VERSION",
    "SUPPORTED_PROTOCOL_VERSIONS",
    "AudioContent",
    "AuthProvider",
    "BlobResourceContents",
    "CallToolResult",
    "CancelledNotification",
    "ClientCapabilities",
    "ContentAnnotations",
    "ContentBlock",
    "EmbeddedResourceContent",
    "ImageContent",
    "Implementation",
    "InitializeParams",
    "InitializeResult",
    "JsonRpcErrorObject",
    "JsonRpcErrorResponse",
    "JsonRpcId",
    "JsonRpcMessage",
    "JsonRpcNotification",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "JsonRpcSuccessResponse",
    "ListResourceTemplatesResult",
    "ListResourcesResult",
    "ListToolsResult",
    "LlmContent",
    "McpAbortError",
    "McpAuthRequiredError",
    "McpClient",
    "McpClientOptions",
    "McpConnectionClosedError",
    "McpError",
    "McpFetch",
    "McpHttpError",
    "McpResponse",
    "McpResponseHeaders",
    "McpSessionExpiredError",
    "McpTimeoutError",
    "McpTransport",
    "McpTransportCloseListener",
    "McpTransportErrorListener",
    "McpTransportMessageListener",
    "ProgressNotification",
    "ReadResourceResult",
    "RequestContext",
    "RequestHandler",
    "Resource",
    "ResourceLinkContent",
    "ResourceTemplate",
    "Root",
    "SendResult",
    "ServerCapabilities",
    "StdioTransport",
    "StdioTransportOptions",
    "StreamableHttpReconnectOptions",
    "StreamableHttpTransport",
    "StreamableHttpTransportOptions",
    "SupportedProtocolVersion",
    "TextContent",
    "TextResourceContents",
    "Tool",
    "ToolAnnotations",
    "ToolExecution",
    "UnauthorizedContext",
    "default_fetch",
    "is_json_rpc_notification",
    "is_json_rpc_request",
    "is_json_rpc_response",
    "parse_json_rpc_message",
    "to_llm_content",
]
